routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



Route::get('/hola', 'UsersController@lista')->name('lista');



Route::group(['prefix'=>'admin'],function(){

Route::resource('users','UsersController');
Route:: get ('users/{id}/destroy',[
    'uses'=>'UsersController@destroy',
    'as'=>'users.destroy',
]);

Route::resource('perfiles','PerfilesController');
Route:: get ('perfiles/{id}/destroy',[
    'uses'=>'PerfilesController@destroy',
    'as'=>'perfiles.destroy',
]);

Route:: resource ('rutinas','RutinasController');
Route:: get ('rutinas/{id}/destroy',[
    'uses'=>'RutinasController@destroy',
    'as'=>'rutinas.destroy'
]);

Route::resource('ejercicios','EjerciciosController');
Route:: get ('ejercicios/{id}/destroy',[
    'uses'=>'EjerciciosController@destroy',
    'as'=>'ejercicios.destroy',
]);


});

app/Ejercicio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ejercicio extends Model
{
    protected $table="ejercicios";
    
    protected $fillable = [
        'id',
        'nombre',
        'musculo',
        'imagen',
    ];

    public function rutina_ejercicio(){
        return $this->hasMany('App\rutina_ejercicio');
    }
}

app/Http/Controllers/EjerciciosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Ejercicio;

class EjerciciosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ejercicios=Ejercicio::orderBy('id', 'asc')->paginate(10);
        
                return view('ejercicios.index')->with(['ejercicios'=> $ejercicios]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('ejercicios.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       
        $ejercicio = new Ejercicio($request->all());
           
        $ejercicio->save();
        flash("Se ha registrado el usuario de forma exitosa")->success()->important();
        
        return redirect()->route('ejercicios.index');
    

  
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ejercicios=Ejercicio :: find($id);
        
        return view('ejercicios.edit')->with('ejercicio', $ejercicios);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $ejercicios=Ejercicio::find($id);
        $ejercicios->fill($request->all());
        $ejercicios->save();
        flash("Se ha editado el ejercicio de forma exitosa")->success()->important();
        return redirect()->route('ejercicios.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $ejercicios=Ejercicio:: find($id);
        $ejercicios->delete();
        flash("Se ha eliminado el ejercicio de forma exitosa")->error()->important();
        return redirect()->route('ejercicios.index');
    }
}

resources/views/ejercicios/create.blade.php
@extends('layout.main')

@section('content')

@if(count($errors)>0)
<div class="alert alert-danger">

  <ul>
    @foreach($errors->all() as $error)
     <li>{{$error}}</li>
     @endforeach
  </ul>

</div>

@endif



<div class="container">
    <div class="">





    <div class="card text-white bg-dark mx-auto mt-5" style="max-width: 40rem;">
  <div class="card-header">
  <h4 class="card-title">Crear Ejercicio</h4>
  </div>
  <div class="card-body">
    

    <form class="form-horizontal" method="POST" action="{{ route('ejercicios.store') }}">
                        {{ csrf_field() }}
                        

                        <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
                            <label for="nombre" class=" control-label">Nombre</label>

                            <div class="">
                                <input id="nombre" type="text" class="form-control" name="nombre" value="{{old('nombre')}}" required autofocus>

                                @if ($errors->has('nombre'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('nombre') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('musculo') ? ' has-error' : '' }}">
                            <label for="musculo" class=" control-label">Musculo</label>

                            <div class="">
                                <input id="musculo" type="text" class="form-control" name="musculo" value="{{old('musculo') }}" required>

                                @if ($errors->has('musculo'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('musculo') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                       


                        <div class="form-group{{ $errors->has('imagen') ? ' has-error' : '' }}">
                        <label for="imagen" class=" control-label">imagen</label>

                        <div class="">
                            <input id="imagen" type="text" class="form-control" name="imagen"  required>

                            @if ($errors->has('imagen'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('imagen') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>




                        
                        <div class="form-group">
                            <div class=" ">
                                <button type="submit" class="btn btn-primary">
                                    Guardar
                                </button>
                                <a class="btn btn-primary  js-scroll-trigger  " href="{{route('ejercicios.index')}}">Volver</a>
                            </div>
                        </div>
                    </form>
  </div>
</div>




    
    </div>
</div>
@endsection

resources/views/ejercicios/edit.blade.php
@extends('layout.main')

@section('content')

@if(count($errors)>0)
<div class="alert alert-danger">

  <ul>
    @foreach($errors->all() as $error)
     <li>{{$error}}</li>
     @endforeach
  </ul>

</div>

@endif



<div class="container">
    <div class="">





    <div class="card text-white bg-dark mx-auto mt-5" style="max-width: 40rem;">
  <div class="card-header">
  <h4 class="card-title">Crear Ejercicio</h4>
  </div>
  <div class="card-body">
    

    <form class="form-horizontal" method="POST" action="{{ route('ejercicios.update',['ejercicio'=>$ejercicio->id])}}">
                        {{ csrf_field() }}
                        {{method_field('PUT')}}
                         
                        

                        <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
                            <label for="nombre" class=" control-label">Nombre</label>

                            <div class="">
                                <input id="nombre" type="text" class="form-control" name="nombre" value="{{ $ejercicio->nombre or old('nombre')}}" required autofocus>

                                @if ($errors->has('nombre'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('nombre') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('musculo') ? ' has-error' : '' }}">
                            <label for="musculo" class=" control-label">Musculo</label>

                            <div class="">
                                <input id="musculo" type="text" class="form-control" name="musculo" value="{{ $ejercicio->musculo or old('musculo') }}" required>

                                @if ($errors->has('musculo'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('musculo') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                       


                        <div class="form-group{{ $errors->has('imagen') ? ' has-error' : '' }}">
                        <label for="imagen" class=" control-label">imagen</label>

                        <div class="">
                            <input id="imagen" type="text" class="form-control" name="imagen" value="{{ $ejercicio->imagen or old('imagen') }}" required  required>

                            @if ($errors->has('imagen'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('imagen') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>




                        
                        <div class="form-group">
                            <div class=" ">
                                <button type="submit" class="btn btn-primary">
                                    Guardar
                                </button>
                                <a class="btn btn-primary  js-scroll-trigger  " href="{{route('ejercicios.index')}}">Volver</a>
                            </div>
                        </div>
                    </form>
  </div>
</div>




    
    </div>
</div>
@endsection

resources/views/ejercicios/index.blade.php
@extends('layout.main')

@section('title','Home')
@section('content')

@include('flash::message')


<div class="container ">

<div class="rounded float-right mt-2 mb-2">
<a href="{{route('ejercicios.create')}}" class="btn btn-dark">Crear Ejercicio</i></a>
</div>

<table class="table table-striped   table-responsive-md table-responsive-sm mx-auto mt-2">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Musculo</th>
      <th scope="col">Imagen</th>
      <th scope="col">Acciónes</th>

    </tr>
  </thead>
  <tbody>
  @foreach($ejercicios as $ejercicio)
    <tr>
      <th scope="row">{{$ejercicio->id}}</th>
      <td>{{$ejercicio->nombre}}</td>
      <td>{{$ejercicio->musculo}}</td>
      <td><img src="{{$ejercicio->imagen}}" style="height:100px; border-radius: 25px"alt=""></td>
  
      <td class="btn-group">
      
      
      <a href="{{route('ejercicios.show',$ejercicio->id)}}" class="btn btn-dark"><i class="fa fa-search" aria-hidden="true"></i></a>
      <a href="{{route('ejercicios.edit',$ejercicio->id)}}" class="btn btn-dark"><i class="fa fa-cogs" aria-hidden="true"></i></a>
      <a href="{{route('ejercicios.destroy',$ejercicio->id)}}" onclick="return confirm('¿Realmente desea eliminar el usuario?')" class="btn btn-danger"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
      
      
      </td>
    </tr>
   
@endforeach
  </tbody>
</table>
<div class="rounded float-right mt-2">
{!!$ejercicios->links()!!}
</div>


</div>
</div>

@endsection