routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



Route::get('/hola', 'UsersController@lista')->name('lista');



Route::group(['prefix'=>'admin'],function(){

Route::resource('users','UsersController');
Route:: get ('users/{id}/destroy',[
    'uses'=>'UsersController@destroy',
    'as'=>'users.destroy',
]);

Route::resource('perfiles','PerfilesController');
Route:: get ('perfiles/{id}/destroy',[
    'uses'=>'PerfilesController@destroy',
    'as'=>'perfiles.destroy',
]);

Route:: resource ('rutinas','RutinasController');
Route:: get ('rutinas/{id}/destroy',[
    'uses'=>'RutinasController@destroy',
    'as'=>'rutinas.destroy'
]);

Route::resource('ejercicios','EjerciciosController');
Route:: get ('ejercicios/{id}/destroy',[
    'uses'=>'EjerciciosController@destroy',
    'as'=>'ejercicios.destroy',
]);


});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 
        'apellido', 
        'email',
        'type', 
        'password',
    ];

    public function historias(){
        return $this->hasMany('App\Historia');
    }

    
    public function rutinas(){
        return $this->hasMany('App\Rutina');
    }
    
    public function perfiles(){
        return $this->hasOne('App\Perfil');
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
         'remember_token',
    ];
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Rutina;
use App\Ejercicios_usuario;
use DB;
class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $users=User::orderBy('id', 'asc')->paginate(10);

        return view('users.index')->with(['users'=> $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        dd('Hola desde controller create user');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.show')->with('user', $user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user=User::find($id);
        
          return view('users.edit')->with('user', $user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $user=User::find($id);
        $user->fill($request->all());
        $user->save();
        flash("Se ha editado el usuario de forma exitosa")->success()->important();
        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user=User:: find($id);
        $user->delete();
        flash("Se ha eliminado el usuario de forma exitosa")->error()->important();
        return redirect()->route('users.index');
    }


    public function lista(){

       $Ejercicios_usuario=Ejercicios_usuario::all();
       $Ejercicios_usuario->user_id = \Auth::user()->id;
       dd($Ejercicios_usuario);
        
       return view('users.index')->with(['users'=> $users]);    
    }
}

resources/views/users/edit.blade.php
@extends('layout.main')

@section('content')

@if(count($errors)>0)
<div class="alert alert-danger">

  <ul>
    @foreach($errors->all() as $error)
     <li>{{$error}}</li>
     @endforeach
  </ul>

</div>

@endif



<div class="container">
    <div class="">





    <div class="card text-white bg-dark mx-auto mt-5" style="max-width: 40rem;">
  <div class="card-header">Header</div>
  <div class="card-body">
    <h4 class="card-title">Dark card title</h4>

    <form class="form-horizontal" method="POST" action="{{ route('users.update',['user'=>$user->id]) }}">
                        {{ csrf_field() }}
                        {{method_field('PUT')}}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class=" control-label">Nombre</label>

                            <div class="">
                                <input id="name" type="text" class="form-control" name="name" value="{{  $user->name or old('name')}}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


                        <div class="form-group{{ $errors->has('apellido') ? ' has-error' : '' }}">
                            <label for="apellido" class=" control-label">Apellido</label>

                            <div class="">
                                <input id="apellido" type="text" class="form-control" name="apellido" value="{{  $user->apellido or old('apellido')}}" required autofocus>

                                @if ($errors->has('apellido'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('apellido') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>



                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class=" control-label">E-Mail</label>

                            <div class="">
                                <input id="email" type="email" class="form-control" name="email" value="{{$user->email or old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                       


                        <div class="form-group{{ $errors->has('type') ? ' has-error' : '' }}">
                            <label for="type" class=" control-label">Tipo</label>

                          
                               
                                <select id="type" class="form-control" name="type" required autofocus>
                              
                                  <option value="member">Usuario</option>
                                  <option value="admin">Administrador</option>
                                 
                                </select>

                                @if ($errors->has('type'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('type') }}</strong>
                                    </span>
                                @endif
                            
                        </div>




                        
                        <div class="form-group">
                            <div class=" ">
                                <button type="submit" class="btn btn-primary">
                                    Guardar
                                </button>
                                <a class="btn btn-primary  js-scroll-trigger  " href="{{route('users.index')}}">Volver</a>
                            </div>
                        </div>
                    </form>
  </div>
</div>




    
    </div>
</div>
@endsection

resources/views/users/home.blade.php
@extends('layout.main')

@section('title','Home')
@section('content')
@include('layout.header')
@include('flash::message')




<section class="bg-primary" id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h2 class="section-heading text-white">We've got what you need!</h2>
            <hr class="light">
            <p class="text-faded">Start Bootstrap has everything you need to get your new website up and running in no time! All of the templates and themes on Start Bootstrap are open source, free to download, and easy to use. No strings attached!</p>
            <a class="btn btn-default btn-xl js-scroll-trigger" href="#services">Get Started!</a>
            

            
          </div>
        </div>
      </div>
    </section>

    <section id="services">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading">At Your Service</h2>
            <hr class="primary">
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box">
              <i class="fa fa-4x fa-diamond text-primary sr-icons"></i>
              <h3>Sturdy Templates</h3>
              <p class="text-muted">Our templates are updated regularly so they don't break.</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box">
              <i class="fa fa-4x fa-paper-plane text-primary sr-icons"></i>
              <h3>Ready to Ship</h3>
              <p class="text-muted">You can use this theme as is, or you can make changes!</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box">
              <i class="fa fa-4x fa-newspaper-o text-primary sr-icons"></i>
              <h3>Up to Date</h3>
              <p class="text-muted">We update dependencies to keep things fresh.</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box">
              <i class="fa fa-4x fa-heart text-primary sr-icons"></i>
              <h3>Made with Love</h3>
              <p class="text-muted">You have to make your websites with love these days!</p>
            </div>
          </div>
        </div>
      </div>
    </section>

  @include('layout.portafolio')

    <div class="call-to-action bg-dark">
      <div class="container text-center">
        <h2>Free Download at Start Bootstrap!</h2>
        <a class="btn btn-default btn-xl sr-button" href="http://startbootstrap.com/template-overviews/creative/">Download Now!</a>
      </div>
    </div>

    <section id="contact">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h2 class="section-heading">Let's Get In Touch!</h2>
            <hr class="primary">
            <p>Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4 ml-auto text-center">
            <i class="fa fa-phone fa-3x sr-contact"></i>
            <p>123-456-6789</p>
          </div>
          <div class="col-lg-4 mr-auto text-center">
            <i class="fa fa-envelope-o fa-3x sr-contact"></i>
            <p>
              <a href="mailto:your-email@your-domain.com">feedback@startbootstrap.com</a>
            </p>
          </div>
        </div>
      </div>
    </section>


@endsection

resources/views/users/index.blade.php
@extends('layout.main')

@section('title','Home')
@section('content')

@include('flash::message')


<div class="container ">

<table class="table table-striped   table-responsive-md table-responsive-sm mx-auto mt-2">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Apellido</th>
      <th scope="col">Email</th>
      <th scope="col">Tipo</th>
      <th scope="col">Acciónes</th>

    </tr>
  </thead>
  <tbody>
  @foreach($users as $user)
    <tr>
      <th scope="row">{{$user->id}}</th>
      <td>{{$user->name}}</td>
      <td>{{$user->apellido}}</td>
      <td>{{$user->email}}</td>
      <td>
      @if($user->type=="admin")
      <span class="badge badge-pill badge-dark">{{ $user->type}}</span>
      @else
      <span class="badge badge-pill badge-info">{{ $user->type}}</span>
      @endif
      </td>
      <td class="btn-group">
      
      
      <a href="{{route('users.show',$user->id)}}" class="btn btn-dark"><i class="fa fa-search" aria-hidden="true"></i></a>
      <a href="{{route('users.edit',$user->id)}}" class="btn btn-dark"><i class="fa fa-cogs" aria-hidden="true"></i></a>
      <a href="{{route('users.destroy',$user->id)}}" onclick="return confirm('¿Realmente desea eliminar el usuario?')" class="btn btn-danger"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
      
      
      </td>
    </tr>
   
@endforeach
  </tbody>
</table>
<div class="rounded float-right mt-2">
{!!$users->links()!!}
</div>


</div>
</div>

@endsection

resources/views/users/show.blade.php
@extends('layout.main')

@section('title','Home')
@section('content')

@include('flash::message')





<div class="card text-white text-center bg-dark mb-3 mt-3 mx-auto" style="max-width: 50rem;">
  <div class="card-header text-capitalize"><strong>{{ $user->name }} {{ $user->apellido }}</strong></div>
  <div class="card-body">
    <p class="card-text">Email:{{ $user->email }}</p>
    <p class="card-text text-capitalize text-center">Tipo: {{ $user->type}}</p>
    <hr>
    <a class="btn btn-primary  js-scroll-trigger  " href="{{route('users.index')}}">Volver</a>

  </div>
</div>


@endsection