routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



Route::get('/hola', 'UsersController@lista')->name('lista');



Route::group(['prefix'=>'admin'],function(){

Route::resource('users','UsersController');
Route:: get ('users/{id}/destroy',[
    'uses'=>'UsersController@destroy',
    'as'=>'users.destroy',
]);

Route::resource('perfiles','PerfilesController');
Route:: get ('perfiles/{id}/destroy',[
    'uses'=>'PerfilesController@destroy',
    'as'=>'perfiles.destroy',
]);

Route:: resource ('rutinas','RutinasController');
Route:: get ('rutinas/{id}/destroy',[
    'uses'=>'RutinasController@destroy',
    'as'=>'rutinas.destroy'
]);

Route::resource('ejercicios','EjerciciosController');
Route:: get ('ejercicios/{id}/destroy',[
    'uses'=>'EjerciciosController@destroy',
    'as'=>'ejercicios.destroy',
]);


});

resources/views/layout/footer.blade.php
<footer class="footer navbar-dark bg-dark text-center">
    <div class="container ">
        <p class="text-white">
          &copy; Jhon Jairo Ovalles
        </p>
    </div>
</footer>

resources/views/layout/header.blade.php
<header class="masthead">
      <div class="header-content">
        <div class="header-content-inner">
          <h1 id="homeHeading">Stargym</h1>
          <hr>
          <p><strong><h2>¡Que te digan que no puedes, es un motivo para demostrarles que estan equivocados!</h2></strong></p>
         
          
        </div>
      </div>
    </header>

resources/views/layout/header2.blade.php
<style>
  .altura{
    height: 10% !important;
    min-height: 300px !important;
    
    padding-bottom: 40px;
  }
</style>


<header class="masthead">
<div class="header-content">
  <div class="header-content-inner">
    <h1 id="homeHeading">Stargym</h1>
    <hr>
    <p><strong><h2>¡Que te digan que no puedes, es un motivo para demostrarles que estan equivocados!</h2></strong></p>
    <!-- <a class="btn btn-primary btn-xl js-scroll-trigger" href="{{ route('login') }}">Ingrea</a> -->

 
    <a class="btn btn-primary btn-xl js-scroll-trigger" href="{{ route('register') }}">Registrate</a>
    
  </div>
</div>
</header>

resources/views/layout/main.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title')</title>  
     
   <link rel="stylesheet" href="{{asset('plugins/bootstrap/css/bootstrap.min.css')}}">
   <link rel="stylesheet" href="{{asset('plugins/fontAwesome/css/font-awesome.min.css')}}">
   <link rel="stylesheet" href="{{asset('css/animate.css')}}">
   <link rel="stylesheet" href="{{asset('css/estilos.css')}}">


   <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
   <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'> 

    <!-- Plugin CSS -->
   <link href="{{asset('css/magnific-popup.css')}}" rel="stylesheet">

    <!-- Custom styles for this template -->
   <link href="{{asset('css/creative.min.css')}}" rel="stylesheet">

   <body id="page-top">
   @include('layout.nav')

    

   <div class="container">
   
   </div>
    @yield('content')



   
  
  <script src="{{asset('plugins/jquery/jquery-3.2.1.min.js')}}"></script>
  <script src="{{asset('plugins/bootstrap/js/popper.min.js')}}"></script>
  <script src="{{asset('plugins/bootstrap/js/bootstrap.min.js')}}"></script>

<!-- Plugin JavaScript -->
    <script src="{{asset('plugins/jquery-easing/jquery.easing.min.js')}}"></script>
    <script src="{{asset('plugins/scrollreveal/scrollreveal.min.js')}}"></script>
    <script src="{{asset('plugins/magnific-popup/jquery.magnific-popup.min.js')}}"></script>

<!-- Custom scripts for this template -->
<script src="{{asset('js/creative.min.js')}}"></script>
</body>
</html>

resources/views/layout/nav.blade.php
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark " id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#"><strong>Star</strong>Gym</a> 
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">


          <ul class="navbar-nav  mx-auto">
        @if (Auth::guest())
        @else
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{{ url('home') }}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#services">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a>
            </li>
            {{--  <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
            </li>
          --}}




@if(Auth::user() and Auth::user()->type=='admin')


<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  Admin
</a>
<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
  <a class="dropdown-item" href="{{route('users.index')}}">Usuarios</a>
  <a class="dropdown-item" href="{{route('rutinas.index')}}">Rutinas</a>
  <a class="dropdown-item" href="{{route('ejercicios.index')}}">Ejercicios</a>
  
</div>
</li>

@endif
      @endguest

          </ul>


   
          <ul class="navbar-nav   float-right">
            <!-- Authentication Links -->
            @if (Auth::guest())
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{{ route('login') }}">Login</a></li>
                <li class="nav-item"><a  class="nav-link js-scroll-trigger"href="{{ route('register') }}">Register</a></li>
            @else
                <li class="dropdown nav-item">
                    <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink1" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                   {{ Auth::user()->name }} <span class="caret"></span>
                    </a>
                         
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink1">
                    <a class="dropdown-item" href="#">
                                Perfil
                            </a>
                            <a class="dropdown-item" href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                         document.getElementById('logout-form').submit();">
                                Logout
                            </a>
                            
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        
                    
                    </div>
            @endguest
        </ul>

        </div>
      </div>
    </nav>

resources/views/layout/nav2.blade.php
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark " id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{{ url('/') }}"><strong>Star</strong>Gym</a> 
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav  mx-auto">
            <!-- <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{{ url('/') }}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#services">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
            </li>
        





            <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Admin
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <!-- <a class="dropdown-item" href="{{route('users.index')}}">Usuarios</a> -->
          <a class="dropdown-item" href="{{route('rutinas.index')}}">Rutinas</a>
          <!-- <a class="dropdown-item" href="{{route('ejercicios.index')}}">Ejercicios</a> -->
          
        </div>
      </li> -->






          </ul>




          <!-- <ul class="navbar-nav  mr-auto">
          <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#portfolio">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Register</a>
            </li>
          </ul> -->


   
          <ul class="navbar-nav  mr-auto">
            <!-- Authentication Links -->
            @if (Auth::guest())
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{{ route('login') }}">Login</a></li>
                <li class="nav-item"><a  class="nav-link js-scroll-trigger"href="{{ route('register') }}">Register</a></li>
            @else
                <li class="dropdown nav-item">
                    <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink1" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                   {{ Auth::user()->name }} <span class="caret"></span>
                    </a>

                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink1">
                  
                            <a class="dropdown-item" href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                         document.getElementById('logout-form').submit();">
                                Logout
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        
                    
                    </div>
            @endguest
        </ul>

        </div>
      </div>
    </nav>

resources/views/layout/portafolio.blade.php
<section class="p-0" id="portfolio">
      <div class="container-fluid">
        <div class="row no-gutter popup-gallery">
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="img/portfolio/fullsize/1.jpg">
              <img class="img-fluid" src="img/portfolio/thumbnails/1.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="img/portfolio/fullsize/2.jpg">
              <img class="img-fluid" src="img/portfolio/thumbnails/2.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="img/portfolio/fullsize/3.jpg">
              <img class="img-fluid" src="img/portfolio/thumbnails/3.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="img/portfolio/fullsize/4.jpg">
              <img class="img-fluid" src="img/portfolio/thumbnails/4.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="img/portfolio/fullsize/5.jpg">
              <img class="img-fluid" src="img/portfolio/thumbnails/5.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="img/portfolio/fullsize/6.jpg">
              <img class="img-fluid" src="img/portfolio/thumbnails/6.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
        </div>
      </div>
    </section>